version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Your Express app port
  better-stack-collector:
    image: betterstack/collector:latest
    environment:
      - COLLECTOR_SECRET=${COLLECTOR_SECRET}
    privileged: true # Required for eBPF
    network_mode: "host" # Recommended for monitoring
